feat(admin-module): base admin module
beeman/fireloop-starter pull request #17
Opened 2017-03-26 21:41 UTC by brannon-darby

2017-03-26 21:46 UTC, beeman requested changes

2017-03-26 21:46 UTC, beeman commented on fireloop/server/model-config.json
> +    "sources": ["loopback/common/models", "loopback/server/models", "../common/models", "./models"],
Please leave the formatting as is here :)

2017-03-26 21:46 UTC, beeman commented on webapp/src/app/admin/dashboard/dashboard.component.ts
> +  // users
Rogue comments?

2017-03-26 21:46 UTC, beeman commented on webapp/src/app/admin/roles/role.component.ts
> +  // subscriptions
Comment is not really informative, might as well go :)

2017-03-26 21:46 UTC, beeman commented on webapp/src/app/admin/roles/role.service.ts
> +    // console.log(fields);
console.log comment

2017-03-26 21:46 UTC, beeman commented on webapp/src/app/admin/users/user.service.ts
> +    // console.log(fields);
console.log

2017-03-26 21:46 UTC, beeman commented on webapp/src/app/home/admin.module.ts
> +<<<<<<< HEAD
Leftovers from a merge

2017-03-26 21:46 UTC, beeman commented on webapp/src/app/home/admin.routing.ts
> +<<<<<<< HEAD
More merge leftovers

2017-03-27 01:01 UTC, jonathan-casarrubias requested changes

2017-03-27 01:01 UTC, jonathan-casarrubias commented on webapp/src/app/admin/admin.module.ts
> +    SDKBrowserModule,
Why importing the SDKBrowserModule in here if it is already imported in app.module?

2017-03-27 14:10 UTC, brannon-darby commented on webapp/src/app/admin/admin.module.ts
> +    SDKBrowserModule,
nice catch, @jonathan-casarrubias

2017-03-27 14:23 UTC, brannon-darby commented on webapp/src/app/admin/admin.module.ts
> +    SDKBrowserModule,
same is true for UiModule, or should that stay?

@beeman @jonathan-casarrubias

2017-03-29 00:45 UTC, jonathan-casarrubias commented on webapp/src/app/admin/admin.module.ts
> +    SDKBrowserModule,
yup

2017-03-29 00:50 UTC, jonathan-casarrubias approved these changes

2017-03-29 02:20 UTC, merged